DATAS SEGMENT
    VAR1 DB 35;
    RES1 DB ;
    RES2 DB ;
DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    PUSH AX;
    MOV AL,VAR1;
    AND AL,0F;
    MOV BL,AL;
    POP AX;
    AND AL,0F0;
    MOV CL,4;
    ROL AL,CL;
    MOV BH,AL;
    MOV RES1,BL;
    MOV RES2,BH;
    AND RES1,0F;
    AND RES2,0F;
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START
