DATAS SEGMENT
    VAR1 DB 35
    RES1 DB ?
    RES2 DB ?
    VAR2 DD 0E2597455H
DATAS ENDS

STACKS SEGMENT
    DW 100H DUP(0)
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
	MOV AX,DATAS;
	MOV DS,AX;
	
    MOV AH,VAR1;
    MOV RES1,AH;
    MOV RES2,AH;
    MOV CL,04H;
    AND RES1,0F0H;
    SHR RES1,CL;
    AND RES2,0FH;
    
    SHL WORD PTR VAR2,1;
    RCL WORD PTR VAR2+2,1;
    
    SHL WORD PTR VAR2,1;
    RCL WORD PTR VAR2+2,1;
    
    
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START
